export interface Insurer {
  id: string;
  name: string;
  logo: string;
  tagline: string;
  color: string;
  rating: number;
  reviews: number;
  appRating: number;
  animals: string[];
  monthlyPrice: Record<string, number>;
  deductible: string;
  reimbursement: string;
  maxAnnual: string;
  waitingPeriod: string;
  features: string[];
  notCovered: string[];
  contact: {
    phone: string;
    website: string;
    email: string;
  };
  claimsTime: string;
}

// Prices shown are approximate starting rates and vary by pet age, breed, and location.
export const insurers: Insurer[] = [
  {
    id: "healthy-paws",
    name: "Healthy Paws",
    logo: "🐾",
    tagline: "No annual or lifetime limits on claim payouts",
    color: "#0066cc",
    rating: 4.8,
    reviews: 26400,
    appRating: 4.7,
    animals: ["dog", "cat"],
    monthlyPrice: { dog: 44, cat: 28, bird: 0, rabbit: 0, reptile: 0, exotic: 0 },
    deductible: "$100–$500",
    reimbursement: "70–90%",
    maxAnnual: "Unlimited",
    waitingPeriod: "15 days illness / 1 day accident",
    features: [
      "Unlimited annual & lifetime payouts",
      "Accidents & illnesses covered",
      "Cancer treatment included",
      "Emergency & specialist care",
      "Hereditary & congenital conditions",
      "Diagnostic tests & imaging",
      "Surgery & hospitalization",
      "Fast mobile app claims",
    ],
    notCovered: [
      "Pre-existing conditions",
      "Wellness & routine care",
      "Breeding & pregnancy costs",
      "Dental illness (disease)",
    ],
    contact: {
      phone: "1-855-898-8991",
      website: "https://www.healthypaws.com",
      email: "customercare@healthypaws.com",
    },
    claimsTime: "2 business days",
  },
  {
    id: "trupanion",
    name: "Trupanion",
    logo: "🦮",
    tagline: "Pays your vet directly — no waiting for reimbursement",
    color: "#DC2626",
    rating: 4.7,
    reviews: 18200,
    appRating: 4.6,
    animals: ["dog", "cat"],
    monthlyPrice: { dog: 58, cat: 36, bird: 0, rabbit: 0, reptile: 0, exotic: 0 },
    deductible: "$0–$1000 (per condition)",
    reimbursement: "90%",
    maxAnnual: "Unlimited",
    waitingPeriod: "30 days illness / 5 days accident",
    features: [
      "Pays vet directly at checkout",
      "90% of actual veterinary costs",
      "Unlimited lifetime payout",
      "Per-condition deductible (pay once)",
      "Hereditary & congenital conditions",
      "Prosthetics & mobility devices",
      "Hydrotherapy & rehabilitation",
      "No payout limits per incident",
    ],
    notCovered: [
      "Pre-existing conditions",
      "Wellness & preventive care",
      "Breeding costs",
      "Taxes on vet services",
    ],
    contact: {
      phone: "1-888-733-2685",
      website: "https://trupanion.com",
      email: "helpme@trupanion.com",
    },
    claimsTime: "Minutes (direct vet pay)",
  },
  {
    id: "embrace",
    name: "Embrace Pet Insurance",
    logo: "💙",
    tagline: "Comprehensive coverage with a diminishing deductible",
    color: "#7C3AED",
    rating: 4.6,
    reviews: 14800,
    appRating: 4.5,
    animals: ["dog", "cat"],
    monthlyPrice: { dog: 40, cat: 22, bird: 0, rabbit: 0, reptile: 0, exotic: 0 },
    deductible: "$200–$1000 (annual)",
    reimbursement: "70–90%",
    maxAnnual: "$5,000–$30,000",
    waitingPeriod: "14 days illness / 2 days accident",
    features: [
      "Diminishing deductible ($50/yr healthy)",
      "Optional Wellness Rewards add-on",
      "Dental illness coverage",
      "Breed-specific conditions covered",
      "Behavioral therapy included",
      "Prescription medications",
      "Curable pre-existing conditions eligible",
      "Flexible annual max & deductible",
    ],
    notCovered: [
      "Pre-existing conditions (incurable)",
      "Cosmetic procedures",
      "Breeding & whelping",
      "Elective & experimental treatments",
    ],
    contact: {
      phone: "1-800-511-9172",
      website: "https://www.embracepetinsurance.com",
      email: "hello@embracepetinsurance.com",
    },
    claimsTime: "5–10 business days",
  },
  {
    id: "nationwide",
    name: "Nationwide Pet",
    logo: "🏛️",
    tagline: "The only major insurer covering exotic pets & birds",
    color: "#1E3A8A",
    rating: 4.3,
    reviews: 21500,
    appRating: 4.1,
    animals: ["dog", "cat", "bird", "rabbit", "reptile", "exotic"],
    monthlyPrice: { dog: 48, cat: 30, bird: 14, rabbit: 18, reptile: 18, exotic: 25 },
    deductible: "$250 (annual)",
    reimbursement: "50–90%",
    maxAnnual: "$7,500–Unlimited",
    waitingPeriod: "14 days illness / 0 days accident",
    features: [
      "Covers exotic pets, birds & reptiles",
      "Whole Pet with Wellness plan option",
      "Routine wellness care covered",
      "Dental illness & injury",
      "Cancer treatment",
      "Hereditary & congenital conditions",
      "Behavioral therapy",
      "Major Medical plan for budget buyers",
    ],
    notCovered: [
      "Pre-existing conditions",
      "Breeding & pregnancy",
      "Elective procedures",
      "Grooming & boarding",
    ],
    contact: {
      phone: "1-877-263-6008",
      website: "https://www.petinsurance.com",
      email: "petinsurance@nationwide.com",
    },
    claimsTime: "5–7 business days",
  },
  {
    id: "aspca",
    name: "ASPCA Pet Health",
    logo: "🐶",
    tagline: "Trusted by millions — backed by the ASPCA name",
    color: "#059669",
    rating: 4.4,
    reviews: 19300,
    appRating: 4.3,
    animals: ["dog", "cat"],
    monthlyPrice: { dog: 36, cat: 23, bird: 0, rabbit: 0, reptile: 0, exotic: 0 },
    deductible: "$100–$500 (annual)",
    reimbursement: "70–90%",
    maxAnnual: "$3,000–$10,000",
    waitingPeriod: "14 days illness / 1 day accident",
    features: [
      "Accident & illness coverage",
      "Preventive care add-on available",
      "Microchipping reimbursement",
      "Lost pet advertising covered",
      "Behavioral issues covered",
      "Hereditary & congenital conditions",
      "Cancer treatment",
      "24/7 virtual vet chat",
    ],
    notCovered: [
      "Pre-existing conditions",
      "Elective & cosmetic procedures",
      "Breeding & pregnancy",
      "Food & dietary supplements",
    ],
    contact: {
      phone: "1-866-204-6764",
      website: "https://www.aspcapetinsurance.com",
      email: "customerservice@aspcapetinsurance.com",
    },
    claimsTime: "3–5 business days",
  },
  {
    id: "lemonade",
    name: "Lemonade Pet",
    logo: "🍋",
    tagline: "AI-powered instant claims — often paid in seconds",
    color: "#FF69B4",
    rating: 4.5,
    reviews: 11700,
    appRating: 4.8,
    animals: ["dog", "cat"],
    monthlyPrice: { dog: 17, cat: 11, bird: 0, rabbit: 0, reptile: 0, exotic: 0 },
    deductible: "$100–$500 (annual)",
    reimbursement: "70–90%",
    maxAnnual: "$5,000–$100,000",
    waitingPeriod: "14 days illness / 2 days accident",
    features: [
      "AI claims — paid in seconds",
      "Lowest starting premiums",
      "Preventive care add-on available",
      "Dental illness covered",
      "Physical therapy & acupuncture",
      "End-of-life & euthanasia costs",
      "Vet visit fees covered",
      "100% digital — no paperwork",
    ],
    notCovered: [
      "Pre-existing conditions",
      "Breeding & pregnancy",
      "Cosmetic & elective procedures",
      "Parasites (preventable)",
    ],
    contact: {
      phone: "1-844-733-8666",
      website: "https://www.lemonade.com/pet",
      email: "hi@lemonade.com",
    },
    claimsTime: "Seconds to minutes (AI)",
  },
  {
    id: "figo",
    name: "Figo Pet Insurance",
    logo: "⚡",
    tagline: "Up to 100% reimbursement with cloud-based claims",
    color: "#0891B2",
    rating: 4.4,
    reviews: 9200,
    appRating: 4.5,
    animals: ["dog", "cat"],
    monthlyPrice: { dog: 38, cat: 24, bird: 0, rabbit: 0, reptile: 0, exotic: 0 },
    deductible: "$100–$1500 (annual)",
    reimbursement: "70–100%",
    maxAnnual: "$5,000–Unlimited",
    waitingPeriod: "14 days illness / 1 day accident",
    features: [
      "100% reimbursement option available",
      "Unlimited annual coverage option",
      "Lost pet recovery costs",
      "Veterinary exam fees covered",
      "Cancer treatment",
      "Hereditary & chronic conditions",
      "Pet Cloud app for records & claims",
      "Emergency boarding covered",
    ],
    notCovered: [
      "Pre-existing conditions",
      "Wellness & routine care (base plan)",
      "Breeding costs",
      "Grooming & training",
    ],
    contact: {
      phone: "1-844-738-3446",
      website: "https://figopetinsurance.com",
      email: "hello@figopetinsurance.com",
    },
    claimsTime: "3–5 business days",
  },
  {
    id: "spot",
    name: "Spot Pet Insurance",
    logo: "🎯",
    tagline: "Fully customizable plans for every budget",
    color: "#D97706",
    rating: 4.3,
    reviews: 8600,
    appRating: 4.2,
    animals: ["dog", "cat"],
    monthlyPrice: { dog: 28, cat: 18, bird: 0, rabbit: 0, reptile: 0, exotic: 0 },
    deductible: "$100–$1000 (annual)",
    reimbursement: "70–90%",
    maxAnnual: "$2,500–Unlimited",
    waitingPeriod: "14 days illness / 1 day accident",
    features: [
      "Highly customizable deductible & limits",
      "Accident-only plan available",
      "Preventive care add-on",
      "Dental illness covered",
      "Behavioral issues covered",
      "Microchipping reimbursement",
      "Poison control consultation covered",
      "Flexible monthly or annual billing",
    ],
    notCovered: [
      "Pre-existing conditions",
      "Elective & cosmetic procedures",
      "Breeding & pregnancy",
      "Experimental treatments",
    ],
    contact: {
      phone: "1-800-905-1595",
      website: "https://www.spotpetins.com",
      email: "hello@spotpetins.com",
    },
    claimsTime: "5–7 business days",
  },
];

export const ANIMAL_TYPES = [
  { id: "all", label: "All", icon: "🐾" },
  { id: "dog", label: "Dog", icon: "🐕" },
  { id: "cat", label: "Cat", icon: "🐈" },
  { id: "bird", label: "Bird", icon: "🦜" },
  { id: "rabbit", label: "Rabbit", icon: "🐇" },
  { id: "reptile", label: "Reptile", icon: "🦎" },
  { id: "exotic", label: "Exotic", icon: "✨" },
];
